-- Schema oluştur
CREATE SCHEMA IF NOT EXISTS gallerist;

-- Veritabanında kolonların sırası JPA/Hibernate tarafından garanti edilmez. Hibernate, kolonları alfabetik veya rastgele sırada oluşturabilir. O yüzden id kolonları başta olacak şekilde sql scripti oluşturuldu.

-- Account tablosu
CREATE TABLE gallerist.account (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   create_time TIMESTAMP(6),
                                   account_no VARCHAR(255),
                                   iban VARCHAR(255),
                                   amount NUMERIC(38,2),
                                   currency_type VARCHAR(255) CHECK (currency_type IN ('TL','USD'))
);

-- Address tablosu
CREATE TABLE gallerist.address (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   create_time TIMESTAMP(6),
                                   city VARCHAR(255),
                                   district VARCHAR(255),
                                   neighborhood VARCHAR(255),
                                   street VARCHAR(255)
);

-- Car tablosu
CREATE TABLE gallerist.car (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               create_time TIMESTAMP(6),
                               brand VARCHAR(255),
                               model VARCHAR(255),
                               plaka VARCHAR(255),
                               production_year INTEGER,
                               price NUMERIC(38,2),
                               damage_price NUMERIC(38,2),
                               car_status_type VARCHAR(255) CHECK (car_status_type IN ('SALABLE','SALED')),
                               currency_type VARCHAR(255) CHECK (currency_type IN ('TL','USD'))
);

-- Customer tablosu
CREATE TABLE gallerist.customer (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    create_time TIMESTAMP(6),
                                    first_name VARCHAR(255),
                                    last_name VARCHAR(255),
                                    tckn VARCHAR(255),
                                    birth_of_date TIMESTAMP(6),
                                    account_id BIGINT UNIQUE,
                                    address_id BIGINT UNIQUE
);

-- Gallerist tablosu
CREATE TABLE gallerist.gallerist (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     create_time TIMESTAMP(6),
                                     first_name VARCHAR(255),
                                     last_name VARCHAR(255),
                                     address_id BIGINT UNIQUE
);

-- Gallerist_Car tablosu
CREATE TABLE gallerist.gallerist_car (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         create_time TIMESTAMP(6),
                                         gallerist_id BIGINT,
                                         car_id BIGINT,
                                         CONSTRAINT uq_gallerist_car UNIQUE (gallerist_id, car_id)
);

-- Refresh_Token tablosu
CREATE TABLE gallerist.refresh_token (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         create_time TIMESTAMP(6),
                                         expired_date TIMESTAMP(6),
                                         user_id BIGINT,
                                         refresh_token VARCHAR(255)
);

-- Saled_Car tablosu
CREATE TABLE gallerist.saled_car (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     create_time TIMESTAMP(6),
                                     gallerist_id BIGINT,
                                     car_id BIGINT,
                                     customer_id BIGINT,
                                     CONSTRAINT uq_gallerist_car_customer UNIQUE (gallerist_id, car_id, customer_id)
);
-- User tablosu
CREATE TABLE gallerist.user (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                create_time TIMESTAMP(6),
                                username VARCHAR(255),
                                password VARCHAR(255)
);

-- Foreign Key'ler
ALTER TABLE gallerist.customer ADD CONSTRAINT fk_customer_account FOREIGN KEY (account_id) REFERENCES gallerist.account(id);
ALTER TABLE gallerist.customer ADD CONSTRAINT fk_customer_address FOREIGN KEY (address_id) REFERENCES gallerist.address(id);
ALTER TABLE gallerist.gallerist ADD CONSTRAINT fk_gallerist_address FOREIGN KEY (address_id) REFERENCES gallerist.address(id);
ALTER TABLE gallerist.gallerist_car ADD CONSTRAINT fk_gallerist_car_gallerist FOREIGN KEY (gallerist_id) REFERENCES gallerist.gallerist(id);
ALTER TABLE gallerist.gallerist_car ADD CONSTRAINT fk_gallerist_car_car FOREIGN KEY (car_id) REFERENCES gallerist.car(id);
ALTER TABLE gallerist.saled_car ADD CONSTRAINT fk_saled_car_gallerist FOREIGN KEY (gallerist_id) REFERENCES gallerist.gallerist(id);
ALTER TABLE gallerist.saled_car ADD CONSTRAINT fk_saled_car_car FOREIGN KEY (car_id) REFERENCES gallerist.car(id);
ALTER TABLE gallerist.saled_car ADD CONSTRAINT fk_saled_car_customer FOREIGN KEY (customer_id) REFERENCES gallerist.customer(id);
ALTER TABLE gallerist.refresh_token ADD CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES gallerist.user(id);